---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: microservices-demo
type: Opaque
stringData:
  api-key: "YOUR_DATADOG_API_KEY"  # Replace with your actual API key or use from environment
  app-key: "YOUR_DATADOG_APP_KEY"  # Optional: Replace with your actual APP key
---
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: microservices-demo
spec:
  global:
    site: us5.datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
  override:
    clusterAgent:
      containers:
        cluster-agent:
          env:
            - name: DD_ADMISSION_CONTROLLER_ADD_AKS_SELECTORS
              value: "true"
