name: App Deployment

on:
  workflow_dispatch:

env:
  IMAGE_NAME_BACKEND: backend-service
  IMAGE_NAME_FRONTEND: frontend-service
  RESOURCE_GROUP: microservices-demo-rg
  ACR_NAME: microservicesacr
  WEBAPP_NAME_BACKEND: microservices-backend
  WEBAPP_NAME_FRONTEND: microservices-frontend
  LOCATION: eastus

jobs:
  build-backend:
    name: Build Backend Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Docker Image
        working-directory: services/backend
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }} .
          docker tag ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }} \
                     ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_BACKEND }}:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Push Image to ACR
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_BACKEND }}:latest

  build-frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Docker Image
        working-directory: services/frontend
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_FRONTEND }}:${{ github.sha }} .
          docker tag ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_FRONTEND }}:${{ github.sha }} \
                     ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_FRONTEND }}:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Push Image to ACR
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_FRONTEND }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_FRONTEND }}:latest

  deploy-backend:
    name: Deploy Backend to Web App
    runs-on: ubuntu-latest
    needs: build-backend

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Web App
        run: |
          az webapp config container set \
            --name ${{ env.WEBAPP_NAME_BACKEND }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }} \
            --docker-registry-server-url https://${{ env.ACR_NAME }}.azurecr.io

      - name: Restart Web App
        run: |
          az webapp restart \
            --name ${{ env.WEBAPP_NAME_BACKEND }} \
            --resource-group ${{ env.RESOURCE_GROUP }}

  deploy-frontend:
    name: Deploy Frontend to Web App
    runs-on: ubuntu-latest
    needs: build-frontend

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Web App
        run: |
          az webapp config container set \
            --name ${{ env.WEBAPP_NAME_FRONTEND }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME_FRONTEND }}:${{ github.sha }} \
            --docker-registry-server-url https://${{ env.ACR_NAME }}.azurecr.io

      - name: Restart Web App
        run: |
          az webapp restart \
            --name ${{ env.WEBAPP_NAME_FRONTEND }} \
            --resource-group ${{ env.RESOURCE_GROUP }}
