name: datadog-deployment

on:
  workflow_dispatch:

jobs:
  deploy-datadog:
    name: Deploy Datadog
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: aks7d0ec772

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy Datadog via Helm
        run: |
          helm repo add datadog https://helm.datadoghq.com
          helm upgrade datadog-operator datadog/datadog-operator
          # kubectl create secret generic datadog-secret --from-literal api-key=2ce086a5998283bf73e095f400bfd685
          kubectl apply -f ./k8s/datadog-agent.yaml
